#master_0:
master_1:
  container_name: imply-poc-druid-master-1
  image: aviata/imply-druid
  command: bin/supervise -c conf/supervise/master-no-zk.conf
  expose:
    - "8081" # Coordinator
    - "8084" # Overlord
  external_links:
    - imply-poc-cassandra:cassandra
    - imply-poc-postgresql:postgresql
    - imply-poc-zookeeper:zookeeper
#data_0:
data_1:
  container_name: imply-poc-druid-data-1
  image: aviata/imply-druid
  command: bin/supervise -c conf/supervise/data.conf
  expose:
    - "8083" # Historical
    - "8085" # Middle Manager
    - "8090" # Indexing Service
  external_links:
    - imply-poc-cassandra:cassandra
    - imply-poc-postgresql:postgresql
    - imply-poc-zookeeper:zookeeper
#query_0:
query_1:
  container_name: imply-poc-druid-query-1
  image: aviata/imply-druid
  command: bin/supervise -c conf/supervise/query.conf
  expose:
    - "8082" # Broker
  ports:
    - "9095:9095" # Bard
  external_links:
    - imply-poc-cassandra:cassandra
    - imply-poc-postgresql:postgresql
    - imply-poc-zookeeper:zookeeper
